---
# tasks file for rpi-pihole-docker
- name: Run PIHole as container
  docker_container:
    name: PIHole
    image: pihole/pihole:latest
    ports:
     - "53:53/tcp"
     - "53:53/udp"
     - "67:67/udp"
     - "80:80/tcp"
     - "443:443/tcp"
    volumes:
     - "/home/pi/etc-pihole/:/etc/pihole/"
     - "/home/pi/etc-dnsmasq.d/:/etc/dnsmasq.d/"
    dns_servers:
     - "127.0.0.1"
     - "8.8.8.8"
    hostname: pi.hole
    env:
     WEBPASSWORD: "pihole1001"
     VIRTUAL_HOST: "pi.hole"
     PROXY_LOCATION: "pi.hole"
     ServerIP: "127.0.0.1"
    restart_policy: unless-stopped

  register: pihole_installation

- name: Debug pihole/pihole
  debug:
    var: pihole_installation
