---
 - hosts: windowsdesk
   tasks:
    - name: Ping
      win_ping:

    - name: Copy file to temp directory
      win_copy:
         src: \\SRV19-001\Shared\create.ps1
         dest: C:\Temp\create.ps1
         remote_src: yes
      become_method: runas
      become: yes