---

- name: Prepare Web Site
  hosts: windowslab
  tasks:
    - name: install iis with sub features
      win_feature:
          name: Web-Server
          state: present
          include_sub_features: yes
          include_management_tools: yes