---
- name: Update repos 
  apt:
    update_cache: yes
    cache_valid_time: 432000
 
- name: Upgrade Apps
  apt:
    upgrade: dist

- name: Check if Pip is already present.
  command: which pip
  failed_when: false
  changed_when: false
  register: pip_command_result

- name: Install Pip if not installed
  apt:
    pkg:
    - python3-pip
  when: pip_command_result.rc == 1

- name: Install git 
  apt:
    pkg:
    - git
